import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#ffb874",
        "error-container": "#ffdad6",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed-variant": "#6a3b00",
        "on-surface-variant": "#424656",
        "surface-container-low": "#f3f4f5",
        "on-error": "#ffffff",
        "surface-container": "#edeeef",
        background: "#f8f9fa",
        "primary-fixed-dim": "#b3c5ff",
        "on-surface": "#191c1d",
        "primary-fixed": "#dae1ff",
        "outline-variant": "#c2c6d8",
        "secondary-fixed": "#ffdcbf",
        "on-secondary-fixed": "#2d1600",
        "on-primary-container": "#f8f7ff",
        error: "#ba1a1a",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#0066ff",
        "on-primary-fixed": "#001849",
        "inverse-on-surface": "#f0f1f2",
        "inverse-primary": "#b3c5ff",
        surface: "#f8f9fa",
        "tertiary-fixed": "#ffdad5",
        "tertiary-fixed-dim": "#ffb4aa",
        primary: "#0050cb",
        "on-tertiary-fixed": "#410001",
        secondary: "#8c5000",
        "tertiary-container": "#de211c",
        "secondary-container": "#fe9400",
        "on-tertiary-container": "#fff6f4",
        "surface-variant": "#e1e3e4",
        "on-secondary-container": "#633700",
        tertiary: "#b60009",
        "on-primary-fixed-variant": "#003fa4",
        outline: "#727687",
        "surface-tint": "#0054d6",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#930005",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-background": "#191c1d",
        "on-error-container": "#93000a",
        "surface-dim": "#d9dadb",
        "surface-bright": "#f8f9fa"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        pill: "9999px",
      },
      spacing: {
        "container-padding": "16px",
        "stack-sm": "4px",
        "stack-md": "12px",
        "stack-lg": "24px",
        base: "8px",
        gutter: "12px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "title-md": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-xl": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      boxShadow: {
        soft: "0 8px 24px rgba(0, 102, 255, 0.08)",
      }
    },
  },
  plugins: [forms],
};
